# Site settings
title: wmServer - Portable HTTP Server for Windows - PHP & MySQL
description: >- # this means to ignore newlines until "baseurl:"
  wmServer is a lightweight, portable HTTP server for Windows with PHP & MySQL. Open-source, no installation required. Easy setup for developers.
url: "https://selvaklnc.github.io/wmserver" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

remote_theme: jekyll/minima
markdown: kramdown

plugins:
  - jekyll-seo-tag
